### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/work/models/image_mean_std/SAR-Intensity/mean.npy'

### ISSUE THREAD

**Issue by Ehsan125** [SpaceNetChallenge/SpaceNet_SAR_Buildings_Solutions#3]
With the reference of previous issues thread, it is the incremental error in next cells, i am attaching the screen shot for your perusal. I am again anticipating that i have to use some config function to location the mean.npy , when i look for intellisense against config variable , it does not open the corresponding function, so again looking for kind consideration. Thank you so much for your previous guidelines. :) 

![Screenshot from 2021-01-20 10-55-10](https://user-images.githubusercontent.com/45161966/105133459-a0c70780-5b0e-11eb-9e3f-421240a2a3a2.png)

**Comment by Ehsan125** [comment]
I have put the below line to reach the correct directory but all in vain. 

`config.MEAN_STD_DIR = "/home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/models/image_mean_std/"`

![Screenshot from 2021-01-20 12-11-27](https://user-images.githubusercontent.com/45161966/105139979-d5d85780-5b18-11eb-9f2c-92c44585080a.png)

**Comment by motokimura** [comment]
Hi @Ehsan125.

This is weird..
Overwriting `MEAN_STD_DIR` should solve the problem.

Did you download `image_mean_std.zip` from [this S3 bucket](https://github.com/SpaceNetChallenge/SpaceNet_SAR_Buildings_Solutions/blob/6a9c3962d987d985384d0d41a187f5fbfadac82c/4-motokimura/Dockerfile#L114)?
Did you extract them under `/home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/models/image_mean_std/` correctly?

Please check if the `mean.npy` and `std.npy` files actually exist under the correct path (= the path which appeared in the error message).

**Comment by motokimura** [comment]
Let me know if that does not help!

We may solve the problem by editing `config.yaml` file directly.

**Comment by Ehsan125** [comment]
files are present in the directory, before i was making the mistake in passing the path, but i later correct the path but still not working, i am attaching the screenshot of path where files are located , and also the error , File are `mean.npy` `std.npy` each file is of `160 Bytes` Please find the screenshots , Thank you 
![Screenshot from 2021-01-25 09-53-49](https://user-images.githubusercontent.com/45161966/105663370-dba4b300-5ef3-11eb-9f3f-dac860403a46.png)
![Screenshot from 2021-01-25 09-54-00](https://user-images.githubusercontent.com/45161966/105663376-e0696700-5ef3-11eb-975b-f8c1202f20c9.png)
![Screenshot from 2021-01-25 09-54-10](https://user-images.githubusercontent.com/45161966/105663381-e2332a80-5ef3-11eb-969e-5254e2b96dc4.png)

**Comment by Ehsan125** [comment]
I think i am not locating the test images path as it is showing in `config.yml` output. I should provide the test images path (of my local system where test images are present), Let me try it...

**Comment by Ehsan125** [comment]
> Let me know if that does not help!
> 
> We may solve the problem by editing `config.yaml` file directly.

I am explicitly passing the location of test images path but there come redundancy of the same attribute in the `config.yml` like there are two 

`

> BOUNDARY_SUBSTRACT_COEFF: 0.2
> BUILDING_MIM_AREA_PIXEL: 0
> BUILDING_SCORE_THRESH: 0.5
> CHECKPOINT_ROOT: /checkpoints
> DATALOADER:
>   TEST_BATCH_SIZE: 8
>   TEST_NUM_WORKERS: 8
>   TRAIN_BATCH_SIZE: 14
>   TRAIN_NUM_WORKERS: 8
>   TRAIN_SHUFFLE: True
>   VAL_BATCH_SIZE: 12
>   VAL_NUM_WORKERS: 8
> DUMP_GIT_INFO: False
> ENSEMBLED_PREDICTION_ROOT: /ensembled_predictions
> ENSEMBLE_EXP_IDS: []
> EVAL:
>   EPOCH_TO_START_VAL: 100
>   MAIN_METRIC: iou/building_footprint
>   METRICS: ['iou']
> EXP_ID: 17
> INPUT:
>   BUILDING_DIR: /wdata/masks
>   CLASSES: ['building_footprint', 'building_boundary']
>   IMAGE_DIR: /data/train/AOI_11_Rotterdam
>   IMAGE_TYPE: SAR-Intensity
>   **_MEAN_STD_DIR: /work/models/image_mean_std_**
>   SAR_ORIENTATION: /work/static/SAR_orientations.txt
>   TEST_IMAGE_DIR: /data/spacenet6/spacenet6/test_public/AOI_11_Rotterdam/SAR-Intensity
>   TRAIN_VAL_SPLIT_DIR: /wdata/split
>   TRAIN_VAL_SPLIT_ID: 2
> LOG_ROOT: /work/models/logs
> **_MEAN_STD_DIR: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/models/image_mean_std/SAR-Intensity/_**
> METHOD_TO_MAKE_POLYGONS: watershed
> MODEL:
>   ACTIVATION: sigmoid
>   ARCHITECTURE: unet
>   BACKBONE: timm-efficientnet-b8
>   DEVICE: cpu
>   ENCODER_PRETRAINED_FROM: advprop
>   FPN_DECODER_DROPOUT: 0.2
>   IN_CHANNELS: 4
>   PSPNET_DROPOUT: 0.2
>   UNET_DECODER_CHANNELS: (256, 128, 64, 32, 16)
>   UNET_ENABLE_DECODER_SCSE: True
>   WEIGHT: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/exp_0017/model_best.pth
> POLY_CSV_ROOT: /polygons
> POLY_OUTPUT_PATH: none
> PREDICTION_ROOT: /predictions
> SAVE_CHECKPOINTS: False
> SOLVER:
>   EPOCHS: 260
>   FOCAL_LOSS_GAMMA: 2.0
>   LOSSES: ['dice', 'bce']
>   LOSS_WEIGHTS: [1.0, 1.0]
>   LR: 0.0001
>   LR_ANNEALING_ETA_MIN: 0.0
>   LR_ANNEALING_T_MAX: 260
>   LR_MULTISTEP_GAMMA: 0.1
>   LR_MULTISTEP_MILESTONES: [230]
>   LR_SCHEDULER: multistep
>   OPTIMIZER: adam
>   WEIGHT_DECAY: 0.0
> **_TEST_IMAGE_DIR: /media/ehsanirshad/Transcend/7-Building_** Detection/Test_Data/test_public/AOI_11_Rotterdam/SAR-Intensity
> TEST_TO_VAL: False
> TRANSFORM:
>   ALIGN_SAR_ORIENTATION: True
>   TARGET_SAR_ORIENTATION: 0
>   TEST_SIZE: (928, 928)
>   TRAIN_HORIZONTAL_FLIP_PROB: 0.0
>   TRAIN_RANDOM_BRIGHTNESS_PROB: 1.0
>   TRAIN_RANDOM_BRIGHTNESS_STD: 0.0
>   TRAIN_RANDOM_CROP_SIZE: (256, 256)
>   TRAIN_RANDOM_ROTATE_DEG: (0, 0)
>   TRAIN_RANDOM_ROTATE_PROB: 1.0
>   TRAIN_SPECKLE_NOISE_PROB: 1.0
>   TRAIN_SPECKLE_NOISE_STD: 0.0
>   TRAIN_VERTICAL_FLIP_PROB: 0.0
> WATERSHED_MAIN_THRESH: 0.3
> WATERSHED_MIN_AREA_PIXEL: 80
> WATERSHED_SEED_MIN_AREA_PIXEL: 20
> WATERSHED_SEED_THRESH: 0.7
> WEIGHT_ROOT: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/

`

I have bold the attributes in the above `config.yml` which are redundant, i want to ask does this creating the problem? Means might be this is creating the confusion of reading the exact path? One more thing that i have noticed that it the redundant lines are not under the same hierarchy as the other attribute is. Like `MEAN_STD_DIR` is under the `INPUT`  while the other redundant  `MEAN_STD_DIR`  is outside the `INPUT` , Can you please anticipate if it is the main source of popping the error? Thank you

**Comment by Ehsan125** [comment]
> > Let me know if that does not help!
> > We may solve the problem by editing `config.yaml` file directly.
> 
> I am explicitly passing the location of test images path but there come redundancy of the same attribute in the `config.yml` like there are two
> 
> `
> 
> > BOUNDARY_SUBSTRACT_COEFF: 0.2
> > BUILDING_MIM_AREA_PIXEL: 0
> > BUILDING_SCORE_THRESH: 0.5
> > CHECKPOINT_ROOT: /checkpoints
> > DATALOADER:
> > TEST_BATCH_SIZE: 8
> > TEST_NUM_WORKERS: 8
> > TRAIN_BATCH_SIZE: 14
> > TRAIN_NUM_WORKERS: 8
> > TRAIN_SHUFFLE: True
> > VAL_BATCH_SIZE: 12
> > VAL_NUM_WORKERS: 8
> > DUMP_GIT_INFO: False
> > ENSEMBLED_PREDICTION_ROOT: /ensembled_predictions
> > ENSEMBLE_EXP_IDS: []
> > EVAL:
> > EPOCH_TO_START_VAL: 100
> > MAIN_METRIC: iou/building_footprint
> > METRICS: ['iou']
> > EXP_ID: 17
> > INPUT:
> > BUILDING_DIR: /wdata/masks
> > CLASSES: ['building_footprint', 'building_boundary']
> > IMAGE_DIR: /data/train/AOI_11_Rotterdam
> > IMAGE_TYPE: SAR-Intensity
> > **_MEAN_STD_DIR: /work/models/image_mean_std_**
> > SAR_ORIENTATION: /work/static/SAR_orientations.txt
> > TEST_IMAGE_DIR: /data/spacenet6/spacenet6/test_public/AOI_11_Rotterdam/SAR-Intensity
> > TRAIN_VAL_SPLIT_DIR: /wdata/split
> > TRAIN_VAL_SPLIT_ID: 2
> > LOG_ROOT: /work/models/logs
> > **_MEAN_STD_DIR: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/models/image_mean_std/SAR-Intensity/_**
> > METHOD_TO_MAKE_POLYGONS: watershed
> > MODEL:
> > ACTIVATION: sigmoid
> > ARCHITECTURE: unet
> > BACKBONE: timm-efficientnet-b8
> > DEVICE: cpu
> > ENCODER_PRETRAINED_FROM: advprop
> > FPN_DECODER_DROPOUT: 0.2
> > IN_CHANNELS: 4
> > PSPNET_DROPOUT: 0.2
> > UNET_DECODER_CHANNELS: (256, 128, 64, 32, 16)
> > UNET_ENABLE_DECODER_SCSE: True
> > WEIGHT: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/exp_0017/model_best.pth
> > POLY_CSV_ROOT: /polygons
> > POLY_OUTPUT_PATH: none
> > PREDICTION_ROOT: /predictions
> > SAVE_CHECKPOINTS: False
> > SOLVER:
> > EPOCHS: 260
> > FOCAL_LOSS_GAMMA: 2.0
> > LOSSES: ['dice', 'bce']
> > LOSS_WEIGHTS: [1.0, 1.0]
> > LR: 0.0001
> > LR_ANNEALING_ETA_MIN: 0.0
> > LR_ANNEALING_T_MAX: 260
> > LR_MULTISTEP_GAMMA: 0.1
> > LR_MULTISTEP_MILESTONES: [230]
> > LR_SCHEDULER: multistep
> > OPTIMIZER: adam
> > WEIGHT_DECAY: 0.0
> > **_TEST_IMAGE_DIR: /media/ehsanirshad/Transcend/7-Building_** Detection/Test_Data/test_public/AOI_11_Rotterdam/SAR-Intensity
> > TEST_TO_VAL: False
> > TRANSFORM:
> > ALIGN_SAR_ORIENTATION: True
> > TARGET_SAR_ORIENTATION: 0
> > TEST_SIZE: (928, 928)
> > TRAIN_HORIZONTAL_FLIP_PROB: 0.0
> > TRAIN_RANDOM_BRIGHTNESS_PROB: 1.0
> > TRAIN_RANDOM_BRIGHTNESS_STD: 0.0
> > TRAIN_RANDOM_CROP_SIZE: (256, 256)
> > TRAIN_RANDOM_ROTATE_DEG: (0, 0)
> > TRAIN_RANDOM_ROTATE_PROB: 1.0
> > TRAIN_SPECKLE_NOISE_PROB: 1.0
> > TRAIN_SPECKLE_NOISE_STD: 0.0
> > TRAIN_VERTICAL_FLIP_PROB: 0.0
> > WATERSHED_MAIN_THRESH: 0.3
> > WATERSHED_MIN_AREA_PIXEL: 80
> > WATERSHED_SEED_MIN_AREA_PIXEL: 20
> > WATERSHED_SEED_THRESH: 0.7
> > WEIGHT_ROOT: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/
> 
> `
> 
> I have bold the attributes in the above `config.yml` which are redundant, i want to ask does this creating the problem? Means might be this is creating the confusion of reading the exact path? One more thing that i have noticed that it the redundant lines are not under the same hierarchy as the other attribute is. Like `MEAN_STD_DIR` is under the `INPUT` while the other redundant `MEAN_STD_DIR` is outside the `INPUT` , Can you please anticipate if it is the main source of popping the error? Thank you

`**config.INPUT.TEST_IMAGE_DIR = "/media/ehsanirshad/Transcend/7-Building Detection/Test_Data/test_public/AOI_11_Rotterdam/SAR-Intensity"**`

I have put the above line to come under the same hierarchy but still problem persist :(

**Comment by motokimura** [comment]
Please add these 2 lines before `config.freeze()`:

```
config.INPUT.MEAN_STD_DIR = "/path/to/your/image_mean_std/"
config.INPUT.TEST_IMAGE_DIR = "/path/to/your/SAR-Intensity/"
```

Please replace the paths based on your environment.

Make sure `mean.npy` and `std.npy` are saved under `image_mean_std` directory.

As you noticed, the hierarchy is important.
`.INPUT` is necessary to update `MEAN_STD_DIR` and `TEST_IMAGE_DIR` parameters correctly.

**Comment by motokimura** [comment]
If the problem still persists, it would be great if you could copy and paste the config (the whole output of `print(config)`) and the whole error message shown in the notebook so that I can understand the problem more clearly.

**Comment by Ehsan125** [comment]
> If the problem still persists, it would be great if you could copy and paste the config (the whole output of `print(config)`) and the whole error message shown in the notebook so that I can understand the problem more clearly.

Thank you and appreciated. Problem related particular to this issue is resolved but now it is giving the following error: I just want to run your `test_spacenet6.ipynb' code to see the results, so needful help require if some more error occurs, Thank you again, here below is next error description:

`TypeError: __init__() missing 1 required positional argument: 'image_paths'`

May i open another issue ? 
![Screenshot from 2021-01-26 08-56-13](https://user-images.githubusercontent.com/45161966/105798643-71077c00-5fb4-11eb-89db-c4c0474f4e79.png)

**Comment by motokimura** [comment]
Sorry, my notebook seems to be dated..

Please try:

```
from glob import glob
image_paths = glob(os.path.join(config.INPUT.TEST_IMAGE_DIR, "*.tif"))

preprocessing = get_preprocess(config, is_test=True)
augmentation = get_augmentation(config, is_train=False)

test_dataset = SpaceNet6TestDataset(
    config,
    image_paths,
    augmentation=augmentation,
    preprocessing=preprocessing
)

test_dataset_vis = SpaceNet6TestDataset(
    config,
    image_paths,
    augmentation=augmentation,
    preprocessing=None
)
```

**Comment by Ehsan125** [comment]
> Sorry, my notebook seems to be dated..
> 
> Please try:
> 
> ```
> from glob import glob
> image_paths = glob(os.path.join(config.INPUT.TEST_IMAGE_DIR, "*.tif"))
> 
> preprocessing = get_preprocess(config, is_test=True)
> augmentation = get_augmentation(config, is_train=False)
> 
> test_dataset = SpaceNet6TestDataset(
>     config,
>     image_paths,
>     augmentation=augmentation,
>     preprocessing=preprocessing
> )
> 
> test_dataset_vis = SpaceNet6TestDataset(
>     config,
>     image_paths,
>     augmentation=augmentation,
>     preprocessing=None
> )
> ```

Here below is the `config` file out put:

> BOUNDARY_SUBSTRACT_COEFF: 0.2
> BUILDING_MIM_AREA_PIXEL: 0
> BUILDING_SCORE_THRESH: 0.5
> CHECKPOINT_ROOT: /checkpoints
> DATALOADER:
>   TEST_BATCH_SIZE: 8
>   TEST_NUM_WORKERS: 8
>   TRAIN_BATCH_SIZE: 14
>   TRAIN_NUM_WORKERS: 8
>   TRAIN_SHUFFLE: True
>   VAL_BATCH_SIZE: 12
>   VAL_NUM_WORKERS: 8
> DUMP_GIT_INFO: False
> ENSEMBLED_PREDICTION_ROOT: /ensembled_predictions
> ENSEMBLE_EXP_IDS: []
> EVAL:
>   EPOCH_TO_START_VAL: 100
>   MAIN_METRIC: iou/building_footprint
>   METRICS: ['iou']
> EXP_ID: 17
> INPUT:
>   BUILDING_DIR: /wdata/masks
>   CLASSES: ['building_footprint', 'building_boundary']
>   IMAGE_DIR: /data/train/AOI_11_Rotterdam
>   IMAGE_TYPE: SAR-Intensity
>   MEAN_STD_DIR: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/models/image_mean_std/
>   SAR_ORIENTATION: /work/static/SAR_orientations.txt
>   TEST_IMAGE_DIR: /media/ehsanirshad/Transcend/7-Building Detection/Test_Data/test_public/AOI_11_Rotterdam/SAR-Intensity
>   TRAIN_VAL_SPLIT_DIR: /wdata/split
>   TRAIN_VAL_SPLIT_ID: 2
> LOG_ROOT: /work/models/logs
> METHOD_TO_MAKE_POLYGONS: watershed
> MODEL:
>   ACTIVATION: sigmoid
>   ARCHITECTURE: unet
>   BACKBONE: timm-efficientnet-b8
>   DEVICE: cpu
>   ENCODER_PRETRAINED_FROM: advprop
>   FPN_DECODER_DROPOUT: 0.2
>   IN_CHANNELS: 4
>   PSPNET_DROPOUT: 0.2
>   UNET_DECODER_CHANNELS: (256, 128, 64, 32, 16)
>   UNET_ENABLE_DECODER_SCSE: True
>   WEIGHT: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/exp_0017/model_best.pth
> POLY_CSV_ROOT: /polygons
> POLY_OUTPUT_PATH: none
> PREDICTION_ROOT: /predictions
> SAVE_CHECKPOINTS: False
> SOLVER:
>   EPOCHS: 260
>   FOCAL_LOSS_GAMMA: 2.0
>   LOSSES: ['dice', 'bce']
>   LOSS_WEIGHTS: [1.0, 1.0]
>   LR: 0.0001
>   LR_ANNEALING_ETA_MIN: 0.0
>   LR_ANNEALING_T_MAX: 260
>   LR_MULTISTEP_GAMMA: 0.1
>   LR_MULTISTEP_MILESTONES: [230]
>   LR_SCHEDULER: multistep
>   OPTIMIZER: adam
>   WEIGHT_DECAY: 0.0
> TEST_TO_VAL: False
> TRANSFORM:
>   ALIGN_SAR_ORIENTATION: True
>   TARGET_SAR_ORIENTATION: 0
>   TEST_SIZE: (928, 928)
>   TRAIN_HORIZONTAL_FLIP_PROB: 0.0
>   TRAIN_RANDOM_BRIGHTNESS_PROB: 1.0
>   TRAIN_RANDOM_BRIGHTNESS_STD: 0.0
>   TRAIN_RANDOM_CROP_SIZE: (256, 256)
>   TRAIN_RANDOM_ROTATE_DEG: (0, 0)
>   TRAIN_RANDOM_ROTATE_PROB: 1.0
>   TRAIN_SPECKLE_NOISE_PROB: 1.0
>   TRAIN_SPECKLE_NOISE_STD: 0.0
>   TRAIN_VERTICAL_FLIP_PROB: 0.0
> WATERSHED_MAIN_THRESH: 0.3
> WATERSHED_MIN_AREA_PIXEL: 80
> WATERSHED_SEED_MIN_AREA_PIXEL: 20
> WATERSHED_SEED_THRESH: 0.7
> WEIGHT_ROOT: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/


and after running the updated file i am getting now the following error: 

> FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-30afd2064bbe> in <module>
      9     image_paths,
     10     augmentation=augmentation,
---> 11     preprocessing=preprocessing
     12 )
     13 

~/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/spacenet6_model/datasets/spacenet6.py in __init__(self, config, image_paths, augmentation, preprocessing)
    114         assert config.TRANSFORM.TARGET_SAR_ORIENTATION in [0, 1]  # north (0) or south (1)
    115         if config.TRANSFORM.ALIGN_SAR_ORIENTATION:
--> 116             self.orientation_df = read_orientation_file(config.INPUT.SAR_ORIENTATION)
    117             self.target_orientation = config.TRANSFORM.TARGET_SAR_ORIENTATION
    118         else:

~/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/spacenet6_model/datasets/utils.py in read_orientation_file(path)
     12         index_col=0,
     13         names=['strip', 'direction'],
---> 14         header=None
     15     )
     16     rotationdf['direction'] = rotationdf['direction'].astype(int)

~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    603     kwds.update(kwds_defaults)
    604 
--> 605     return _read(filepath_or_buffer, kwds)
    606 
    607 

~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    455 
    456     # Create the parser.
--> 457     parser = TextFileReader(filepath_or_buffer, **kwds)
    458 
    459     if chunksize or iterator:

~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    812             self.options["has_index_names"] = kwds["has_index_names"]
    813 
--> 814         self._engine = self._make_engine(self.engine)
    815 
    816     def close(self):

~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1043             )
   1044         # error: Too many arguments for "ParserBase"
-> 1045         return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
   1046 
   1047     def _failover_to_python(self):

~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1860 
   1861         # open handles
-> 1862         self._open_handles(src, kwds)
   1863         assert self.handles is not None
   1864         for key in ("storage_options", "encoding", "memory_map", "compression"):

~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in _open_handles(self, src, kwds)
   1361             compression=kwds.get("compression", None),
   1362             memory_map=kwds.get("memory_map", False),
-> 1363             storage_options=kwds.get("storage_options", None),
   1364         )
   1365 

~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    642                 encoding=ioargs.encoding,
    643                 errors=errors,
--> 644                 newline="",
    645             )
    646         else:

FileNotFoundError: [Errno 2] No such file or directory: '/work/static/SAR_orientations.txt'

**Comment by Ehsan125** [comment]
> > Sorry, my notebook seems to be dated..
> > Please try:
> > ```
> > from glob import glob
> > image_paths = glob(os.path.join(config.INPUT.TEST_IMAGE_DIR, "*.tif"))
> > 
> > preprocessing = get_preprocess(config, is_test=True)
> > augmentation = get_augmentation(config, is_train=False)
> > 
> > test_dataset = SpaceNet6TestDataset(
> >     config,
> >     image_paths,
> >     augmentation=augmentation,
> >     preprocessing=preprocessing
> > )
> > 
> > test_dataset_vis = SpaceNet6TestDataset(
> >     config,
> >     image_paths,
> >     augmentation=augmentation,
> >     preprocessing=None
> > )
> > ```
> 
> Here below is the `config` file out put:
> 
> > BOUNDARY_SUBSTRACT_COEFF: 0.2
> > BUILDING_MIM_AREA_PIXEL: 0
> > BUILDING_SCORE_THRESH: 0.5
> > CHECKPOINT_ROOT: /checkpoints
> > DATALOADER:
> > TEST_BATCH_SIZE: 8
> > TEST_NUM_WORKERS: 8
> > TRAIN_BATCH_SIZE: 14
> > TRAIN_NUM_WORKERS: 8
> > TRAIN_SHUFFLE: True
> > VAL_BATCH_SIZE: 12
> > VAL_NUM_WORKERS: 8
> > DUMP_GIT_INFO: False
> > ENSEMBLED_PREDICTION_ROOT: /ensembled_predictions
> > ENSEMBLE_EXP_IDS: []
> > EVAL:
> > EPOCH_TO_START_VAL: 100
> > MAIN_METRIC: iou/building_footprint
> > METRICS: ['iou']
> > EXP_ID: 17
> > INPUT:
> > BUILDING_DIR: /wdata/masks
> > CLASSES: ['building_footprint', 'building_boundary']
> > IMAGE_DIR: /data/train/AOI_11_Rotterdam
> > IMAGE_TYPE: SAR-Intensity
> > MEAN_STD_DIR: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/models/image_mean_std/
> > SAR_ORIENTATION: /work/static/SAR_orientations.txt
> > TEST_IMAGE_DIR: /media/ehsanirshad/Transcend/7-Building Detection/Test_Data/test_public/AOI_11_Rotterdam/SAR-Intensity
> > TRAIN_VAL_SPLIT_DIR: /wdata/split
> > TRAIN_VAL_SPLIT_ID: 2
> > LOG_ROOT: /work/models/logs
> > METHOD_TO_MAKE_POLYGONS: watershed
> > MODEL:
> > ACTIVATION: sigmoid
> > ARCHITECTURE: unet
> > BACKBONE: timm-efficientnet-b8
> > DEVICE: cpu
> > ENCODER_PRETRAINED_FROM: advprop
> > FPN_DECODER_DROPOUT: 0.2
> > IN_CHANNELS: 4
> > PSPNET_DROPOUT: 0.2
> > UNET_DECODER_CHANNELS: (256, 128, 64, 32, 16)
> > UNET_ENABLE_DECODER_SCSE: True
> > WEIGHT: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/exp_0017/model_best.pth
> > POLY_CSV_ROOT: /polygons
> > POLY_OUTPUT_PATH: none
> > PREDICTION_ROOT: /predictions
> > SAVE_CHECKPOINTS: False
> > SOLVER:
> > EPOCHS: 260
> > FOCAL_LOSS_GAMMA: 2.0
> > LOSSES: ['dice', 'bce']
> > LOSS_WEIGHTS: [1.0, 1.0]
> > LR: 0.0001
> > LR_ANNEALING_ETA_MIN: 0.0
> > LR_ANNEALING_T_MAX: 260
> > LR_MULTISTEP_GAMMA: 0.1
> > LR_MULTISTEP_MILESTONES: [230]
> > LR_SCHEDULER: multistep
> > OPTIMIZER: adam
> > WEIGHT_DECAY: 0.0
> > TEST_TO_VAL: False
> > TRANSFORM:
> > ALIGN_SAR_ORIENTATION: True
> > TARGET_SAR_ORIENTATION: 0
> > TEST_SIZE: (928, 928)
> > TRAIN_HORIZONTAL_FLIP_PROB: 0.0
> > TRAIN_RANDOM_BRIGHTNESS_PROB: 1.0
> > TRAIN_RANDOM_BRIGHTNESS_STD: 0.0
> > TRAIN_RANDOM_CROP_SIZE: (256, 256)
> > TRAIN_RANDOM_ROTATE_DEG: (0, 0)
> > TRAIN_RANDOM_ROTATE_PROB: 1.0
> > TRAIN_SPECKLE_NOISE_PROB: 1.0
> > TRAIN_SPECKLE_NOISE_STD: 0.0
> > TRAIN_VERTICAL_FLIP_PROB: 0.0
> > WATERSHED_MAIN_THRESH: 0.3
> > WATERSHED_MIN_AREA_PIXEL: 80
> > WATERSHED_SEED_MIN_AREA_PIXEL: 20
> > WATERSHED_SEED_THRESH: 0.7
> > WEIGHT_ROOT: /home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/
> 
> and after running the updated file i am getting now the following error:
> 
> > FileNotFoundError                         Traceback (most recent call last)
> >  in 
> > 9     image_paths,
> > 10     augmentation=augmentation,
> > ---> 11     preprocessing=preprocessing
> > 12 )
> > 13
> 
> ~/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/spacenet6_model/datasets/spacenet6.py in **init**(self, config, image_paths, augmentation, preprocessing)
> 114 assert config.TRANSFORM.TARGET_SAR_ORIENTATION in [0, 1] # north (0) or south (1)
> 115 if config.TRANSFORM.ALIGN_SAR_ORIENTATION:
> --> 116 self.orientation_df = read_orientation_file(config.INPUT.SAR_ORIENTATION)
> 117 self.target_orientation = config.TRANSFORM.TARGET_SAR_ORIENTATION
> 118 else:
> 
> ~/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/spacenet6_model/datasets/utils.py in read_orientation_file(path)
> 12 index_col=0,
> 13 names=['strip', 'direction'],
> ---> 14 header=None
> 15 )
> 16 rotationdf['direction'] = rotationdf['direction'].astype(int)
> 
> ~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
> 603 kwds.update(kwds_defaults)
> 604
> --> 605 return _read(filepath_or_buffer, kwds)
> 606
> 607
> 
> ~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
> 455
> 456 # Create the parser.
> --> 457 parser = TextFileReader(filepath_or_buffer, **kwds)
> 458
> 459 if chunksize or iterator:
> 
> ~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in **init**(self, f, engine, **kwds)
> 812 self.options["has_index_names"] = kwds["has_index_names"]
> 813
> --> 814 self._engine = self._make_engine(self.engine)
> 815
> 816 def close(self):
> 
> ~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
> 1043 )
> 1044 # error: Too many arguments for "ParserBase"
> -> 1045 return mapping[engine](self.f, **self.options) # type: ignore[call-arg]
> 1046
> 1047 def _failover_to_python(self):
> 
> ~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in **init**(self, src, **kwds)
> 1860
> 1861 # open handles
> -> 1862 self._open_handles(src, kwds)
> 1863 assert self.handles is not None
> 1864 for key in ("storage_options", "encoding", "memory_map", "compression"):
> 
> ~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/parsers.py in _open_handles(self, src, kwds)
> 1361 compression=kwds.get("compression", None),
> 1362 memory_map=kwds.get("memory_map", False),
> -> 1363 storage_options=kwds.get("storage_options", None),
> 1364 )
> 1365
> 
> ~/anaconda3/envs/solaris/lib/python3.7/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
> 642 encoding=ioargs.encoding,
> 643 errors=errors,
> --> 644 newline="",
> 645 )
> 646 else:
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/work/static/SAR_orientations.txt'

I have resolved this `orientation.txt` error.

**Comment by Ehsan125** [comment]
`config.INPUT.SAR_ORIENTATION="/home/ehsanirshad/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/static/SAR_orientations.txt"` 

I have put the above line and cell get successfully ran. Now try to run another cells. Thank you
